#!/usr/bin/python

import click
import subprocess as sub

@click.command()
@click.option('--host', '-h', default='yoyo')
@click.option('--user', '-u', default='life')
@click.option('--ip', '-i', default='127.0.0.1')
@click.option('--key', '-k', default='~/.ssh/id_rsa')
def add_host_config(host, user, ip, key):
    config = "Host %s\n" % host
    config += "User %s\n" % user
    config += "HostName %s\n" % ip
    config += "IdentityFile %s\n" % key
    cmd = 'echo "' + config + '">> ~/.ssh/config'
    sub.Popen([cmd], shell=True)

if __name__=='__main__':
    add_host_config()
    
